use ventas_jugos;\

create table tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) null,
BARRIO VARCHAR(50) null,
COMISION float null,
FECHA_ADMISION DATE null,
VACACIONES BIT (1) null,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_producto(
CODIGO VARCHAR (10) NOT NULL,
DESCRIPCION VARCHAR (100) NULL,
SABOR VARCHAR (50) NULL,
TAMANO VARCHAR (50) NULL,
ENVASE VARCHAR (50) NULL, 
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

DROP TABLE tb_vendedor;